<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_save_add_to_group</name>
   <tag></tag>
   <elementGuidId>18a4c783-2131-4870-bced-f3d570f37599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-root/div[@class='container-fluid']/div[@class='row']//authorization-list/kendo-dialog//button[.='Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-root/div[@class='container-fluid']/div[@class='row']//authorization-list/kendo-dialog//button[.='Save']</value>
   </webElementProperties>
</WebElementEntity>
