<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_upc_selectppgs</name>
   <tag></tag>
   <elementGuidId>23dfa617-51b0-488e-8536-90dec7eb0020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='float-left']/dropdown-filterable[2]/div[@class='filter-container']//span[@class='k-select']//following-sibling::span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='float-left']/dropdown-filterable[2]/div[@class='filter-container']//span[@class='k-select']//following-sibling::span</value>
   </webElementProperties>
</WebElementEntity>
