<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbl_UPCActivation_table_headers</name>
   <tag></tag>
   <elementGuidId>46d50f62-6874-4d42-ae3c-ea54fda2b436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//kendo-tabstrip/div[2]//kendo-grid//div[@role='presentation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//kendo-tabstrip/div[2]//kendo-grid//div[@role='presentation']</value>
   </webElementProperties>
</WebElementEntity>
