<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Baseplanning</name>
   <tag></tag>
   <elementGuidId>90a19f41-076e-4130-9803-267e500aec5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//kendo-tabstrip/ul[@role='tablist']/li[2]/span[@class='k-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//kendo-tabstrip/ul[@role='tablist']/li[2]/span[@class='k-link']</value>
   </webElementProperties>
</WebElementEntity>
