<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ddb_viewlist</description>
   <name>ddb_viewlist</name>
   <tag></tag>
   <elementGuidId>5a080535-4331-417c-aded-7e36abc0b687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Standard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Standard']</value>
   </webElementProperties>
</WebElementEntity>
