<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddb_product_selection</name>
   <tag></tag>
   <elementGuidId>3731e1e5-0a7d-4ec1-bd26-98522888828c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//kendo-combobox/span/kendo-searchbar/following-sibling::span[@class='k-select']/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//kendo-combobox/span/kendo-searchbar/following-sibling::span[@class='k-select']/span</value>
   </webElementProperties>
</WebElementEntity>
