<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbl_rows</name>
   <tag></tag>
   <elementGuidId>073b7654-de7d-41ad-8ca5-b2b35b2bd48c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='k-tabstrip-tabpanel-0']/product-costing/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/product-costing/div/div[3]/div</value>
   </webElementProperties>
</WebElementEntity>
