<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_category</name>
   <tag></tag>
   <elementGuidId>e6e7fc6d-9af4-4c7d-81e4-2a19800c3375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='row']/kendo-dropdownlist[3]/span[@role='listbox']//span[@class='k-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='row']/kendo-dropdownlist[3]/span[@role='listbox']//span[@class='k-input']</value>
   </webElementProperties>
</WebElementEntity>
