<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbl_gridlayout</name>
   <tag></tag>
   <elementGuidId>4dcc2448-71db-41d5-9ea7-b3c6fee0ed8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//compare-plans/div[2]/div[2]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//compare-plans/div[2]/div[2]/table/tbody/tr/td</value>
   </webElementProperties>
</WebElementEntity>
