<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddb_verify_category</name>
   <tag></tag>
   <elementGuidId>32f9fa5b-c8a7-4478-ba52-84bf63d4c9a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//compass-plan-selection-header-component/div[2]/div[2]/span[3]/kendo-dropdownlist/span[@role='listbox']//span[@class='k-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//compass-plan-selection-header-component/div[2]/div[2]/span[3]/kendo-dropdownlist/span[@role='listbox']//span[@class='k-input']</value>
   </webElementProperties>
</WebElementEntity>
